#!/bin/bash

PROJECT=es-source-db
SERVERS=elastic-group
gcloud=/usr/bin/gcloud
port=9200

sudo cp -f /opt/haproxy/haproxy.cfg.template /opt/haproxy/haproxy.cfg

for machine in $($gcloud compute instances list --project=$PROJECT | grep $SERVERS | awk {'print $1'}); do
    sudo echo "    server $machine $machine:$port check" >> /opt/haproxy/haproxy.cfg
done

# check if config files do not match
if [ "$(diff /etc/haproxy/haproxy.cfg /opt/haproxy/haproxy.cfg | tr -d '\n' | cut -c1-4 )" != "" ]
then
  echo "Updating /etc/haproxy/haproxy.cfg !!!"
  sudo cp -fr /opt/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg
  echo "Restarting haproxy !!!"
  sudo systemctl restart haproxy.service
fi
els=''
for machine in $(gcloud compute instances list | grep elastic-group | awk {'print $1'}); do
        els=$els,\"$machine\"
done
 echo $els | sed 's/^.//' > restr
 echo $restr
 discovery.zen.ping.unicast.hosts: ["pro-elastic-admin","elastic-group-dvvh","elastic-group-gqln","elastic-group-l9ez"]
